ledgerPluginInfo:
  -
    validatorID: sUr7d10R
    validatorType: legacy-socketio
    validatorURL: https://sawtooth-validator:5140
    validatorKeyPath: /etc/cactus/connector-sawtooth-socketio/CA/connector.crt
    maxCounterRequestID: 100
    syncFunctionTimeoutMillisecond: 5000
    socketOptions:
      rejectUnauthorized: false
      reconnection: false
      timeout: 20000
    ledgerInfo:
      ledgerAbstract: Sawtooth Ledger
    apiInfo: []
