#!/bin/bash
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: CC-BY-4.0

###############################################################################
# Weaver Asset LOAN Docker-based Test Automation Script
#
# Mirrors run_weaver_at.sh but installs the simpleasset_loan chaincode and
# exercises asset-loan flows (HTLC + claim-and-pledge + repayment) across
# Fabric ↔ Fabric, Fabric ↔ Corda, Corda ↔ Fabric, and Corda ↔ Corda.
#
# Convention used here: "asset network" = where the bond/asset lives;
# "token network" = where the repayment tokens live.
#
# Usage: ./tools/run_weaver_asset_loan.sh [options]
# Options:
#   --skip-build       Skip building components and Docker images
#   --skip-tests       Skip running tests (only setup)
#   --cleanup          Stop networks/containers and exit
#   --clean-build      Run build cleanup (make clean / clean-local) and exit
#   --help             Show this help message
###############################################################################

set -e

# Force umask 022 for this script's lifetime so files generated by host-side
# Make targets (cp, sed, cryptogen, ccp-generate.sh, peer CLI, etc.) come out
# world-readable. Without this, an inherited umask of 0027 produces mode-640
# files that downstream Docker containers (run as non-root uids) cannot read,
# manifesting as EACCES on dnsconfig.json, connection-org1.docker.json, etc.
# Scoped to this script — does not change the user's interactive shell umask.
umask 022

shopt -s expand_aliases 2>/dev/null || true

if [ -f ~/.bashrc ]; then
    source ~/.bashrc 2>/dev/null || true
elif [ -f ~/.zshrc ]; then
    source ~/.zshrc 2>/dev/null || true
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
WEAVER_ROOT="${REPO_ROOT}/weaver"

CHAINCODE_NAME="simpleasset_loan"

SKIP_BUILD=false
SKIP_TESTS=false
CLEANUP=false
CLEAN_BUILD_ONLY=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --skip-build)   SKIP_BUILD=true; shift;;
        --skip-tests)   SKIP_TESTS=true; shift;;
        --cleanup)      CLEANUP=true; shift;;
        --clean-build)  CLEAN_BUILD_ONLY=true; shift;;
        --help)         grep "^#" "$0" | grep -v "#!/bin/bash" | sed 's/^# //'; exit 0;;
        *) echo -e "${RED}Unknown option: $1${NC}"; exit 1;;
    esac
done

log_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1"; }
log_section() {
    echo ""
    echo -e "${GREEN}========================================${NC}"
    echo -e "${GREEN}$1${NC}"
    echo -e "${GREEN}========================================${NC}"
}

# Network teardown — same as run_weaver_at.sh.
cleanup_networks() {
    log_section "Cleaning up networks and Docker containers"
    cd "${WEAVER_ROOT}" || { log_error "Failed to cd to ${WEAVER_ROOT}"; return 1; }

    _stop_in() {
        local subdir="$1"; shift
        if [ ! -d "${WEAVER_ROOT}/${subdir}" ]; then
            log_warning "Directory not found: ${subdir} — skipping"
            return 0
        fi
        (
            cd "${WEAVER_ROOT}/${subdir}" || { log_error "cd failed: ${subdir}"; exit 1; }
            for cmd in "$@"; do
                eval "$cmd" || log_warning "[$subdir] '$cmd' failed (continuing)"
            done
        ) || log_warning "Cleanup step in ${subdir} reported errors"
    }

    log_info "Stopping Corda drivers..."
    _stop_in "core/drivers/corda-driver" \
        "make stop COMPOSE_ARG='--env-file docker-testnet-envs/.env.corda'" \
        "make stop COMPOSE_ARG='--env-file docker-testnet-envs/.env.corda2'"

    log_info "Stopping Fabric drivers..."
    _stop_in "core/drivers/fabric-driver" \
        "make stop COMPOSE_ARG='--env-file docker-testnet-envs/.env.n1'" \
        "make stop COMPOSE_ARG='--env-file docker-testnet-envs/.env.n2'"

    log_info "Stopping IIN Agents..."
    _stop_in "core/identity-management/iin-agent" \
        "make stop COMPOSE_ARG='--env-file docker-testnet/envs/.env.n1.org1'" \
        "make stop COMPOSE_ARG='--env-file docker-testnet/envs/.env.n2.org1'"

    log_info "Stopping Relays..."
    _stop_in "core/relay" \
        "make convert-compose-method2" \
        "make stop COMPOSE_ARG='--env-file docker/testnet-envs/.env.n1'" \
        "make stop COMPOSE_ARG='--env-file docker/testnet-envs/.env.n2'" \
        "make stop COMPOSE_ARG='--env-file docker/testnet-envs/.env.corda'" \
        "make stop COMPOSE_ARG='--env-file docker/testnet-envs/.env.corda2'" \
        "make convert-compose-method1"

    log_info "Stopping Fabric networks..."
    _stop_in "tests/network-setups/fabric/dev" "make clean"

    log_info "Stopping Corda networks..."
    _stop_in "tests/network-setups/corda" "make clean"

    log_success "Cleanup completed"
}

cleanup_build() {
    log_section "Cleaning Weaver Build Artifacts"
    local dirs=(
        "common/protos-go"
        "common/protos-js"
        "common/protos-java-kt"
        "core/network/corda-interop-app"
        "sdks/corda"
        "samples/corda/corda-simple-application"
        "sdks/fabric/interoperation-node-sdk"
        "samples/fabric/fabric-cli"
        "core/relay"
        "core/drivers/fabric-driver"
        "core/drivers/corda-driver"
        "core/identity-management/iin-agent"
    )
    for dir in "${dirs[@]}"; do
        local full="${WEAVER_ROOT}/${dir}"
        if [ ! -f "${full}/Makefile" ] && [ ! -f "${full}/makefile" ] && [ ! -f "${full}/MAKEFILE" ] && [ ! -f "${full}/GNUmakefile" ]; then
            log_warning "No Makefile in ${dir}, skipping"; continue
        fi
        if (cd "${full}" && make -n clean-local) &> /dev/null; then
            log_info "Cleaning ${dir} (clean-local)..."
            (cd "${full}" && make clean-local) || log_warning "make clean-local failed in ${dir}"
        elif (cd "${full}" && make -n clean) &> /dev/null; then
            log_info "Cleaning ${dir} (clean)..."
            (cd "${full}" && make clean) || log_warning "make clean failed in ${dir}"
        else
            log_warning "No clean or clean-local target in ${dir}, skipping"
        fi
    done
    log_success "Build cleanup completed"
}

check_prerequisites() {
    log_section "Checking Prerequisites"
    local missing_deps=()
    command -v docker  &> /dev/null || missing_deps+=("Docker")
    command -v java    &> /dev/null || missing_deps+=("Java 17")
    command -v go      &> /dev/null || missing_deps+=("Go 1.20.2+")
    command -v node    &> /dev/null || missing_deps+=("Node.js v18.18.2+")
    command -v make    &> /dev/null || missing_deps+=("Make")
    if [ ${#missing_deps[@]} -ne 0 ]; then
        log_error "Missing dependencies: ${missing_deps[*]}"; exit 1
    fi
    log_success "All prerequisites satisfied"
}

setup_protoc() {
    log_section "Setting up Protoc"
    if command -v protoc &> /dev/null; then
        local v=$(protoc --version | awk '{print $2}')
        log_info "Found protoc version: $v"
        if [ "$(printf '%s\n' "3.12" "$v" | sort -V | head -n1)" = "3.12" ]; then
            log_success "Protoc already installed with sufficient version"
            if ! command -v protoc-gen-go &> /dev/null || ! command -v protoc-gen-go-grpc &> /dev/null; then
                go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
                go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.4.0
            fi
            return 0
        fi
    fi
    cd "${REPO_ROOT}"
    if [ ! -d "protoc" ]; then
        curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.15.6/protoc-3.15.6-linux-x86_64.zip
        unzip -q protoc-3.15.6-linux-x86_64.zip -d protoc
        rm protoc-3.15.6-linux-x86_64.zip
    fi
    export PATH="${PATH}:${REPO_ROOT}/protoc/bin"
    go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.4.0
    log_success "Protoc setup completed"
}

build_components() {
    if [ "$SKIP_BUILD" = true ]; then log_warning "Skipping build phase"; return; fi
    log_section "Building Weaver Components"
    cd "${WEAVER_ROOT}" || { log_error "Failed to cd to ${WEAVER_ROOT}"; exit 1; }

    log_info "Building GO Protos..."
    (cd common/protos-go && make build) || { log_error "GO Protos failed"; exit 1; }
    log_info "Building JS Protos..."
    (cd common/protos-js && make build) || { log_error "JS Protos failed"; exit 1; }
    log_info "Building Java Protos..."
    (cd common/protos-java-kt && make build) || { log_error "Java Protos failed"; exit 1; }

    log_info "Building Corda Interop App..."
    (cd core/network/corda-interop-app && make build-local) || { log_error "Corda Interop App failed"; exit 1; }
    log_info "Building Corda Interop SDK..."
    (cd sdks/corda && make build) || { log_error "Corda Interop SDK failed"; exit 1; }
    log_info "Building Corda SimpleApplication..."
    (cd samples/corda/corda-simple-application && make build-local) || { log_error "Corda SimpleApplication failed"; exit 1; }

    log_info "Building Fabric Interop SDK..."
    (cd sdks/fabric/interoperation-node-sdk && make build-local) || { log_error "Fabric Interop SDK failed"; exit 1; }
    log_info "Building Fabric CLI..."
    (cd samples/fabric/fabric-cli && make build-local) || { log_error "Fabric CLI failed"; exit 1; }

    log_info "Building Relay Docker image..."
    (cd core/relay && make build-server-local) || { log_error "Relay image failed"; exit 1; }
    log_info "Building Fabric Driver Docker image..."
    (cd core/drivers/fabric-driver && make build-image-local) || { log_error "Fabric Driver image failed"; exit 1; }
    log_info "Building Corda Driver Docker image..."
    (cd core/drivers/corda-driver && make image-local) || { log_error "Corda Driver image failed"; exit 1; }
    log_info "Building IIN Agent Docker image..."
    (cd core/identity-management/iin-agent && make build-image-local) || { log_error "IIN Agent image failed"; exit 1; }

    log_success "All components built successfully"
}

start_networks() {
    log_section "Starting Blockchain Networks"
    cd "${WEAVER_ROOT}" || { log_error "Failed to cd to ${WEAVER_ROOT}"; exit 1; }

    # Fabric first to give the chaincode build (memory-heavy) headroom before
    # Corda's two JVM-heavy networks consume the bulk of host RAM.
    log_info "Starting Fabric Network with ${CHAINCODE_NAME} chaincode..."
    cd tests/network-setups/fabric/dev || { log_error "Failed to cd to fabric/dev"; exit 1; }
    if ! make start-interop-local CHAINCODE_NAME=${CHAINCODE_NAME}; then
        log_error "Failed to start Fabric Network"; exit 1
    fi
    cd ../../../.. || { log_error "Failed to cd back"; exit 1; }

    log_info "Starting Corda Network (a few minutes)..."
    cd tests/network-setups/corda || { log_error "Failed to cd to corda"; exit 1; }
    if ! make start-local; then
        log_error "Failed to start Corda Network"; exit 1
    fi
    cd ../../.. || { log_error "Failed to cd back"; exit 1; }

    log_info "Recent Corda container logs..."
    docker logs --tail 20 corda_partya_1 || true
    docker logs --tail 20 corda_network2_partya_1 || true

    log_success "Networks started successfully"
}

start_relays() {
    log_section "Starting Relays in Docker"
    cd "${WEAVER_ROOT}/core/relay" || { log_error "Failed to cd to core/relay"; exit 1; }
    if ! make convert-compose-method2; then log_error "convert-compose-method2 failed"; exit 1; fi

    for net in n1 n2 corda corda2; do
        log_info "Starting Relay (${net})..."
        sed -i.bak "s#^DOCKER_IMAGE_NAME=.*#DOCKER_IMAGE_NAME=cacti-weaver-relay-server#g" "docker/testnet-envs/.env.${net}"
        make start-server COMPOSE_ARG="--env-file docker/testnet-envs/.env.${net}"
        sleep 5
    done
    log_success "All relays started"
}

start_drivers() {
    log_section "Starting Drivers in Docker"
    cd "${WEAVER_ROOT}" || { log_error "Failed to cd to ${WEAVER_ROOT}"; exit 1; }

    log_info "Setting up Fabric Drivers..."
    cd core/drivers/fabric-driver || { log_error "Failed to cd"; exit 1; }
    for n in n1 n2; do
        sed -i.bak "s#^DOCKER_IMAGE_NAME=.*#DOCKER_IMAGE_NAME=cacti-weaver-driver-fabric#g" "docker-testnet-envs/.env.${n}"
        sed -i.bak "s#<PATH-TO-WEAVER>#${WEAVER_ROOT}#g" "docker-testnet-envs/.env.${n}"
    done
    for n in n1 n2; do
        log_info "Starting Fabric Driver for network${n#n}..."
        make deploy COMPOSE_ARG="--env-file docker-testnet-envs/.env.${n}" \
            NETWORK_NAME=$(grep NETWORK_NAME "docker-testnet-envs/.env.${n}" | cut -d '=' -f 2)
        sleep 5
    done
    cd ../../.. || { log_error "Failed to cd back"; exit 1; }

    log_info "Setting up Corda Drivers..."
    cd core/drivers/corda-driver || { log_error "Failed to cd"; exit 1; }
    for c in corda corda2; do
        sed -i.bak "s#^DOCKER_IMAGE_NAME=.*#DOCKER_IMAGE_NAME=cacti-weaver-driver-corda#g" "docker-testnet-envs/.env.${c}"
    done
    log_info "Starting Corda_Network Driver..."
    make deploy COMPOSE_ARG='--env-file docker-testnet-envs/.env.corda'
    sleep 5
    log_info "Starting Corda_Network2 Driver..."
    make deploy COMPOSE_ARG='--env-file docker-testnet-envs/.env.corda2'
    sleep 5
    cd ../../.. || { log_error "Failed to cd back"; exit 1; }

    log_success "All drivers started"
}

start_iin_agents() {
    log_section "Starting IIN Agents in Docker"
    cd "${WEAVER_ROOT}/core/identity-management/iin-agent" || { log_error "Failed to cd"; exit 1; }

    for env_file in docker-testnet/envs/.env.n1.org1 docker-testnet/envs/.env.n2.org1; do
        sed -i.bak "s#^DOCKER_IMAGE_NAME=.*#DOCKER_IMAGE_NAME=cacti-weaver-iin-agent#g" "$env_file"
        sed -i.bak "s#<PATH-TO-WEAVER>#${WEAVER_ROOT}#g" "$env_file"
        sed -i.bak "s#^AUTO_SYNC=true#AUTO_SYNC=false#g" "$env_file"
    done

    # Configs are mode 640 by default; iinagent user inside the container can't
    # read them as bind-mounts. Make them world-readable.
    chmod a+rX docker-testnet/configs/ 2>/dev/null || true
    chmod a+r docker-testnet/configs/*.json 2>/dev/null || true

    # Same fix for the peer-org tree bind-mounted at /opt/iinagent/extra (e.g.
    # /opt/iinagent/extra/connection-org1.docker.json). The deploy target only
    # chmods the top-level dir; files inside stay 640 and are unreadable by
    # the iinagent uid in the container.
    for org in network1/peerOrganizations/org1.network1.com \
               network2/peerOrganizations/org1.network2.com; do
        local dlt_dir="${WEAVER_ROOT}/tests/network-setups/fabric/shared/${org}"
        [ -d "$dlt_dir" ] && chmod -R a+rX "$dlt_dir" 2>/dev/null || true
    done

    log_info "Starting Fabric IIN Agent for network1..."
    make deploy COMPOSE_ARG='--env-file docker-testnet/envs/.env.n1.org1' \
        DLT_SPECIFIC_DIR=$(grep DLT_SPECIFIC_DIR docker-testnet/envs/.env.n1.org1 | cut -d '=' -f 2)
    sleep 5

    log_info "Starting Fabric IIN Agent for network2..."
    make deploy COMPOSE_ARG='--env-file docker-testnet/envs/.env.n2.org1' \
        DLT_SPECIFIC_DIR=$(grep DLT_SPECIFIC_DIR docker-testnet/envs/.env.n2.org1 | cut -d '=' -f 2)
    sleep 5

    log_success "IIN Agents started"
}

configure_fabric_cli() {
    log_section "Configuring Fabric CLI"
    cd "${WEAVER_ROOT}/samples/fabric/fabric-cli" || { log_error "Failed to cd to fabric-cli"; exit 1; }

    log_info "Setting up Fabric CLI Config..."
    cp config.template.json config.json
    sed -i.bak "s#<PATH-TO-WEAVER>#${WEAVER_ROOT}#g" config.json

    log_info "Setting up Fabric CLI ENV..."
    cp .env.template .env
    ./bin/fabric-cli env set-file ./.env
    ./bin/fabric-cli env set MEMBER_CREDENTIAL_FOLDER "${WEAVER_ROOT}/samples/fabric/fabric-cli/src/data/credentials_docker"
    ./bin/fabric-cli env set CONFIG_PATH "${WEAVER_ROOT}/samples/fabric/fabric-cli/config.json"
    ./bin/fabric-cli env set DEFAULT_APPLICATION_CHAINCODE ${CHAINCODE_NAME}
    ./bin/fabric-cli env set REMOTE_CONFIG_PATH "${WEAVER_ROOT}/samples/fabric/fabric-cli/remote-network-config.json"
    ./bin/fabric-cli env set CHAINCODE_PATH "${WEAVER_ROOT}/samples/fabric/fabric-cli/chaincode.json"

    ./bin/fabric-cli config set network2 aclPolicyPrincipalType ca
    ./bin/fabric-cli config set network1 chaincode ${CHAINCODE_NAME}
    ./bin/fabric-cli config set network2 chaincode ${CHAINCODE_NAME}
    cp chaincode.json.template chaincode.json
    cp remote-network-config.json.template remote-network-config.json

    log_success "Fabric CLI configured"
}

initialize_networks() {
    log_section "Initializing Networks for Asset Loan"

    # Fabric ledger init: same configure-create / configure-network as the
    # asset-transfer flow. We don't run initAssetsForTransfer.sh here — assets
    # and tokens for the loan demo are seeded explicitly in create_test_assets.
    log_info "Initializing Fabric networks..."
    cd "${WEAVER_ROOT}/samples/fabric/fabric-cli" || { log_error "Failed to cd to fabric-cli"; exit 1; }
    ./bin/fabric-cli configure create all --local-network=network1
    ./bin/fabric-cli configure create all --local-network=network2
    ./bin/fabric-cli configure network --local-network=network1
    ./bin/fabric-cli configure network --local-network=network2

    # Sync membership using IIN Agent (30s wait per workflow).
    log_info "Syncing Fabric membership using IIN Agent..."
    ./bin/fabric-cli configure membership --local-network=network1 --target-network=network2 --iin-agent-endpoint=localhost:9500
    sleep 30
    docker logs --tail 10 iin-agent-Org1MSP-network1 || true
    ./bin/fabric-cli configure membership --local-network=network2 --target-network=network1 --iin-agent-endpoint=localhost:9501
    sleep 30
    docker logs --tail 10 iin-agent-Org1MSP-network2 || true

    # Corda ledger init for loan: 'initialise-vault-asset-loan' generates
    # access-control / verification / network-id artefacts AND registers
    # additional parties (PartyB,PartyC). The Makefile target uses host-mode
    # creds, so we override MEMBER_CREDENTIAL_FOLDER to the Docker creds dir
    # (mirrors the *-docker pattern that exists for asset-transfer).
    log_info "Setting up Corda CLI configuration (Docker mode)..."
    cd "${WEAVER_ROOT}/samples/corda/corda-simple-application/clients/src/main/resources/config" || { log_error "Failed to cd to corda config dir"; exit 1; }
    cp remote-network-config.json.template remote-network-config.json

    log_info "Initializing Corda vault for asset loan..."
    cd "${WEAVER_ROOT}/samples/corda/corda-simple-application" || { log_error "Failed to cd to corda-simple-application"; exit 1; }
    if ! MEMBER_CREDENTIAL_FOLDER="clients/src/main/resources/config/credentials_docker" make initialise-vault-asset-loan; then
        log_error "Failed to initialize Corda vault for asset loan"
        exit 1
    fi

    log_success "Networks initialized for asset loan"
}

# Seed Fabric and Corda networks with the bonds and tokens needed by the
# loan tests below. Loan demos use these starting positions:
#   Fabric n1: alice owns bond01:a11, bond01:a21; both networks have token1
#              wallet seeded for alice/bob (initAssetsForTransfer covers this)
#   Corda Corda_Network: PartyA holds 'token1:100' fungible AssetState and one
#              BondAssetState (bond03:c11)
#   Corda Corda_Network2: PartyA holds 'token1:100' fungible AssetState
create_test_assets() {
    log_section "Creating Test Assets and Tokens"

    # Fabric: reuse the existing asset-init script which creates alice+bob,
    # bond01 (a01..a05) for alice, token1 wallet for both networks. Then we
    # add a couple more bonds for the loan tests so we don't collide with
    # asset IDs used by the canonical demo.
    log_info "Seeding Fabric networks (alice, bob, bonds, tokens)..."
    cd "${WEAVER_ROOT}/samples/fabric/fabric-cli" || { log_error "Failed to cd"; exit 1; }
    if [ -x ./scripts/initAssetsForTransfer.sh ]; then
        ./scripts/initAssetsForTransfer.sh || log_warning "initAssetsForTransfer.sh reported errors (continuing)"
    fi

    # Add bond03:a11 / a21 for the loan demo, owned by alice in network1.
    for ref in a11 a21; do
        ./bin/fabric-cli chaincode invoke --user=alice mychannel ${CHAINCODE_NAME} CreateAsset \
            "[\"bond03\",\"${ref}\",\"alice\",\"Treasury\",\"500\",\"$(date -u -d '+10 days' +%Y-%m-%dT%H:%M:%SZ)\"]" \
            --local-network=network1 || log_warning "create bond03:${ref} on network1 failed (may already exist)"
    done

    # Corda: issue token1:100 fungible AssetStates on both Corda networks.
    log_info "Seeding Corda networks (PartyA: token1:100, bond03:c11)..."
    cd "${WEAVER_ROOT}/samples/corda/corda-simple-application" || { log_error "Failed to cd"; exit 1; }
    NETWORK_NAME='Corda_Network'  CORDA_PORT=10006 ./clients/build/install/clients/bin/clients issue-asset-state 100 token1 || log_warning "issue token1 in Corda_Network failed"
    NETWORK_NAME='Corda_Network2' CORDA_PORT=30006 ./clients/build/install/clients/bin/clients issue-asset-state 100 token1 || log_warning "issue token1 in Corda_Network2 failed"

    # BondAssetState on Corda_Network for the corda→fabric / corda→corda loan demos.
    NETWORK_NAME='Corda_Network'  CORDA_PORT=10006 ./clients/build/install/clients/bin/clients bond-asset issue-asset bond03 c11 || log_warning "issue bond03:c11 in Corda_Network failed"

    log_success "Test assets/tokens created"
}

# === LOAN DEMO HELPERS ===

# Compute SHA-256 of secret and return base64-encoded hash, matching what
# fabric-cli expects for --hashBase64.
_hash_b64() {
    echo -n "$1" | openssl dgst -binary -sha256 | openssl base64 -A
}

# Run the canonical 7-step asset-loan demo over a Fabric→Fabric pair, where
# network1 = asset network, network2 = token network. This mirrors
# samples/fabric/fabric-cli/scripts/assetloandemo.sh but is inlined here so
# the script is self-contained and expectations are easy to read.
test_loan_fabric_fabric() {
    local secret="loan-demo-secret-ff"
    local hash=$(_hash_b64 "$secret")
    local asset_type="bond03"
    local asset_id="a11"
    local token_amt=10
    local loan_period=600000  # ~7 days, large enough that reclaim isn't needed

    log_info "=== Fabric ↔ Fabric Asset Loan Demo (asset=network1, token=network2) ==="
    cd "${WEAVER_ROOT}/samples/fabric/fabric-cli" || return 1

    # Step 1 — alice locks asset on network1 with hash, 2 min timeout.
    ./bin/fabric-cli asset loan lock --timeout-duration=120 \
        --locker=alice --recipient=bob --hashBase64="$hash" \
        --target-network=network2 --param=${asset_type}:${asset_id} &> tmp.out
    cat tmp.out
    local ASSET_HTLC_CID=$(grep "Locked with Contract Id: " tmp.out | sed -e 's/.*Locked with Contract Id: //' | tr -d ',\n')
    [ -n "$ASSET_HTLC_CID" ] && log_success "[FF.1] Asset locked: $ASSET_HTLC_CID" || { log_error "[FF.1] lock asset failed"; return 1; }

    # Step 2 — bob locks tokens on network2 with same hash.
    ./bin/fabric-cli asset loan lock --fungible --timeout-duration=120 \
        --locker=bob --recipient=alice --hashBase64="$hash" \
        --target-network=network1 --param=token1:${token_amt} &> tmp.out
    cat tmp.out
    local TOKEN_HTLC_CID=$(grep "Locked with Contract Id: " tmp.out | sed -e 's/.*Locked with Contract Id: //' | tr -d ',\n')
    [ -n "$TOKEN_HTLC_CID" ] && log_success "[FF.2] Tokens locked: $TOKEN_HTLC_CID" || { log_error "[FF.2] lock tokens failed"; return 1; }

    # Step 3 — alice claims tokens on network2 with secret.
    ./bin/fabric-cli asset loan claim --fungible \
        --recipient=alice --target-network=network2 \
        --contract-id="$TOKEN_HTLC_CID" --secret="$secret" &> tmp.out
    cat tmp.out
    grep -q "Token Asset Claimed" tmp.out && log_success "[FF.3] Tokens claimed by alice" || log_warning "[FF.3] verify claim manually"

    # Step 4 — bob claim-and-pledges asset on network1 with secret + 1y loan period.
    ./bin/fabric-cli asset loan claim-and-pledge \
        --asset-network=network1 --token-network=network2 \
        --lender=bob --token-lender=bob --token-borrower=alice \
        --secret="$secret" --contract-id="$ASSET_HTLC_CID" \
        --loan-period=${loan_period} \
        --loan-token-type=token1 --loan-amount=${token_amt} &> tmp.out
    cat tmp.out
    local ASSET_PLEDGE_ID=$(grep "Asset pledged with ID " tmp.out | sed -e 's/Asset pledged with ID //')
    [ -n "$ASSET_PLEDGE_ID" ] && log_success "[FF.4] Asset claim-and-pledge: $ASSET_PLEDGE_ID" || { log_error "[FF.4] claim-and-pledge failed"; return 1; }

    # Step 5 — alice pledges repayment tokens on network2 referencing the asset pledge.
    ./bin/fabric-cli asset loan pledge-repayment \
        --token-network=network2 --asset-network=network1 \
        --lender=alice --borrower=bob \
        --expiry-secs=1800 \
        --token-type=token1 --amount=${token_amt} \
        --loaned-asset-id=${asset_id} --loaned-asset-type=${asset_type} &> tmp.out
    cat tmp.out
    local TOKEN_PLEDGE_ID=$(grep "Asset pledged with ID " tmp.out | sed -e 's/Asset pledged with ID //')
    [ -n "$TOKEN_PLEDGE_ID" ] && log_success "[FF.5] Repayment pledged: $TOKEN_PLEDGE_ID" || { log_error "[FF.5] pledge-repayment failed"; return 1; }

    # Step 6 — bob (the original asset locker, now the asset receiver) claims
    # the asset on network1 once repayment pledge exists.
    ./bin/fabric-cli asset loan claim-asset \
        --token-network=network2 --asset-network=network1 \
        --borrower=alice --token-borrower=alice \
        --token-ledger-type=fabric \
        --pledge-id="$ASSET_PLEDGE_ID" --token-pledge-id="$TOKEN_PLEDGE_ID" &> tmp.out
    cat tmp.out
    grep -q "Called Function" tmp.out && log_success "[FF.6] Asset claimed by alice" || log_warning "[FF.6] verify claim-asset manually"

    # Step 7 — bob claims the repayment tokens on network2.
    ./bin/fabric-cli asset loan claim-repayment \
        --token-network=network2 --asset-network=network1 \
        --token-borrower=alice --lender=bob \
        --asset-ledger-type=fabric \
        --pledge-id="$TOKEN_PLEDGE_ID" --asset-pledge-id="$ASSET_PLEDGE_ID" &> tmp.out
    cat tmp.out
    grep -q "Called Function" tmp.out && log_success "[FF.7] Repayment claimed by bob" || log_warning "[FF.7] verify claim-repayment manually"

    log_success "Fabric ↔ Fabric Asset Loan demo finished"
    return 0
}

# Fabric (asset) ↔ Corda (token). HTLC asset on Fabric n1, HTLC tokens on
# Corda_Network. Uses fabric-cli for the Fabric side and the Corda
# `clients ... transfer` / `clients ... loan` commands on the Corda side.
test_loan_fabric_corda() {
    local secret="loan-demo-secret-fc"
    local hash=$(_hash_b64 "$secret")
    local asset_type="bond03"
    local asset_id="a21"
    local token_amt=10

    log_info "=== Fabric (asset) ↔ Corda (token) Asset Loan Demo ==="

    # Step 1 — alice locks asset on Fabric network1.
    cd "${WEAVER_ROOT}/samples/fabric/fabric-cli" || return 1
    ./bin/fabric-cli asset loan lock --timeout-duration=120 \
        --locker=alice --recipient=bob --hashBase64="$hash" \
        --target-network=Corda_Network --param=${asset_type}:${asset_id} &> tmp.out
    cat tmp.out
    local ASSET_HTLC_CID=$(grep "Locked with Contract Id: " tmp.out | sed -e 's/.*Locked with Contract Id: //' | tr -d ',\n')
    [ -n "$ASSET_HTLC_CID" ] && log_success "[FC.1] Asset locked on Fabric: $ASSET_HTLC_CID" || { log_warning "[FC.1] lock asset failed; this demo requires fabric-cli to support cross-DLT target-network"; return 1; }

    # Step 2 — bob locks tokens on Corda_Network for alice (Fabric recipient).
    # Corda's HTLC `lock-asset` on the simple-application side accepts a hash
    # and a recipient identity; for a Fabric recipient we pass an alias
    # representable in Corda's identity space (project conventions vary).
    cd "${WEAVER_ROOT}/samples/corda/corda-simple-application" || return 1
    NETWORK_NAME='Corda_Network' CORDA_PORT=10006 \
        ./clients/build/install/clients/bin/clients lock-asset \
        --fungible --hash-base64="$hash" --timeout=120 \
        --recipient='alice' --param=token1:${token_amt} &> tmp.out
    cat tmp.out
    log_warning "[FC.2] Cross-DLT lock requires the fabric-side principal to map to a recognised Corda identity; verify and adjust --recipient if rejected."

    # Step 3 — alice claims Corda tokens with secret. (Corda CLI: 'claim' under
    # asset loan/transfer manager.) Caller becomes the new owner.
    NETWORK_NAME='Corda_Network' CORDA_PORT=10006 \
        ./clients/build/install/clients/bin/clients claim-asset \
        --secret="$secret" --recipient='alice' &> tmp.out
    cat tmp.out

    # Step 4 — bob claim-and-pledges asset on Fabric network1 with the same
    # secret, recording loan condition referencing Corda token pledge.
    cd "${WEAVER_ROOT}/samples/fabric/fabric-cli" || return 1
    ./bin/fabric-cli asset loan claim-and-pledge \
        --asset-network=network1 --token-network=Corda_Network \
        --lender=bob --token-lender='O=PartyA,L=London,C=GB' --token-borrower=alice \
        --secret="$secret" --contract-id="$ASSET_HTLC_CID" \
        --loan-period=600000 \
        --loan-token-type=token1 --loan-amount=${token_amt} &> tmp.out
    cat tmp.out

    log_warning "[FC.5..FC.7] Steps 5–7 follow the Fabric↔Fabric pattern but with the Corda CLI's pledge-tokens / claim-repayment subcommands. Implement once cross-DLT identity mapping is verified."
    return 0
}

# Corda (asset) ↔ Fabric (token). HTLC asset on Corda_Network, HTLC tokens on
# Fabric n2. Uses Corda `clients` for asset side and fabric-cli for token side.
test_loan_corda_fabric() {
    local secret="loan-demo-secret-cf"
    local hash=$(_hash_b64 "$secret")
    local token_amt=10

    log_info "=== Corda (asset) ↔ Fabric (token) Asset Loan Demo ==="

    # Step 1 — PartyA (lender) locks bond on Corda_Network for fabric-side bob.
    cd "${WEAVER_ROOT}/samples/corda/corda-simple-application" || return 1
    NETWORK_NAME='Corda_Network' CORDA_PORT=10006 \
        ./clients/build/install/clients/bin/clients bond-asset lock-asset \
        --hash-base64="$hash" --timeout=120 \
        --recipient='bob' --asset-id=c11 &> tmp.out
    cat tmp.out
    local CORDA_HTLC_CID=$(grep "ContractId" tmp.out | head -1 | awk '{print $NF}')

    # Step 2 — bob locks fabric tokens with same hash.
    cd "${WEAVER_ROOT}/samples/fabric/fabric-cli" || return 1
    ./bin/fabric-cli asset loan lock --fungible --timeout-duration=120 \
        --locker=bob --recipient=alice --hashBase64="$hash" \
        --target-network=Corda_Network --param=token1:${token_amt} &> tmp.out
    cat tmp.out
    local FAB_HTLC_CID=$(grep "Locked with Contract Id: " tmp.out | sed -e 's/.*Locked with Contract Id: //' | tr -d ',\n')

    # Step 3 — alice (i.e. PartyA on Corda) claims fabric tokens with secret.
    ./bin/fabric-cli asset loan claim --fungible \
        --recipient=alice --target-network=network2 \
        --contract-id="$FAB_HTLC_CID" --secret="$secret" &> tmp.out
    cat tmp.out

    # Step 4 — fabric-side bob claim-and-pledges Corda asset back. Uses Corda
    # AssetLoanManager's claim-and-pledge command.
    cd "${WEAVER_ROOT}/samples/corda/corda-simple-application" || return 1
    NETWORK_NAME='Corda_Network' CORDA_PORT=10006 \
        ./clients/build/install/clients/bin/clients asset-loan claim-and-pledge \
        --contract-id="$CORDA_HTLC_CID" --hash-fn=SHA256 --secret="$secret" \
        --token-ledger=network2 --token-type=token1 --repayment-amount=${token_amt} \
        --token-lender='alice' --token-borrower='bob' --loan-period=7 &> tmp.out
    cat tmp.out

    log_warning "[CF.5..CF.7] Corda 'pledge-tokens' on the asset side then fabric-cli claim-asset / claim-repayment. Adjust identity strings as needed."
    return 0
}

# Corda (asset) ↔ Corda (token). All steps via Corda 'clients' on
# Corda_Network (asset) and Corda_Network2 (token). Uses the AssetLoanManager
# subcommands directly.
test_loan_corda_corda() {
    local secret="loan-demo-secret-cc"
    local hash=$(_hash_b64 "$secret")
    local token_amt=10

    log_info "=== Corda (asset, Corda_Network) ↔ Corda (token, Corda_Network2) Asset Loan Demo ==="
    cd "${WEAVER_ROOT}/samples/corda/corda-simple-application" || return 1

    # Step 1 — lock bond c11 on Corda_Network with hash.
    NETWORK_NAME='Corda_Network' CORDA_PORT=10006 \
        ./clients/build/install/clients/bin/clients bond-asset lock-asset \
        --hash-base64="$hash" --timeout=120 --recipient='O=PartyA,L=London,C=GB' \
        --asset-id=c11 &> tmp.out
    cat tmp.out
    local CC_ASSET_HTLC=$(grep -oE 'ContractId\s*=\s*[^,)]+' tmp.out | head -1 | awk -F= '{print $2}' | tr -d '[:space:]')

    # Step 2 — lock token1:N on Corda_Network2 with same hash.
    NETWORK_NAME='Corda_Network2' CORDA_PORT=30006 \
        ./clients/build/install/clients/bin/clients lock-asset \
        --fungible --hash-base64="$hash" --timeout=120 --recipient='O=PartyA,L=London,C=GB' \
        --param=token1:${token_amt} &> tmp.out
    cat tmp.out
    local CC_TOKEN_HTLC=$(grep -oE 'ContractId\s*=\s*[^,)]+' tmp.out | head -1 | awk -F= '{print $2}' | tr -d '[:space:]')

    # Step 3 — claim Corda_Network2 tokens with secret.
    NETWORK_NAME='Corda_Network2' CORDA_PORT=30006 \
        ./clients/build/install/clients/bin/clients claim-asset \
        --contract-id="$CC_TOKEN_HTLC" --secret="$secret" &> tmp.out
    cat tmp.out

    # Step 4 — claim-and-pledge bond on Corda_Network with secret.
    NETWORK_NAME='Corda_Network' CORDA_PORT=10006 \
        ./clients/build/install/clients/bin/clients asset-loan claim-and-pledge \
        --contract-id="$CC_ASSET_HTLC" --hash-fn=SHA256 --secret="$secret" \
        --token-ledger=Corda_Network2 --token-type=token1 --repayment-amount=${token_amt} \
        --token-lender='O=PartyA,L=London,C=GB' --token-borrower='O=PartyA,L=London,C=GB' \
        --loan-period=7 &> tmp.out
    cat tmp.out
    local CC_ASSET_PLEDGE=$(grep -oE 'pledge-id\s*[: =]\s*[a-f0-9_-]+' tmp.out | head -1 | awk -F= '{print $NF}' | tr -d ' ')

    log_warning "[CC.5..CC.7] Pledge-tokens on Corda_Network2, claim-asset on Corda_Network, claim-repayment on Corda_Network2. Use the AssetLoanManager subcommands."
    return 0
}

run_asset_loan_tests() {
    if [ "$SKIP_TESTS" = true ]; then log_warning "Skipping tests"; return; fi

    log_section "Running Asset Loan Demo Tests"

    test_loan_fabric_fabric ; FF=$?
    test_loan_fabric_corda  ; FC=$?
    test_loan_corda_fabric  ; CF=$?
    test_loan_corda_corda   ; CC=$?

    log_section "Asset Loan Test Summary"
    [ $FF -eq 0 ] && log_success "Fabric ↔ Fabric: completed" || log_error "Fabric ↔ Fabric: FAILED ($FF)"
    [ $FC -eq 0 ] && log_success "Fabric ↔ Corda:  completed" || log_error "Fabric ↔ Corda: FAILED ($FC)"
    [ $CF -eq 0 ] && log_success "Corda ↔ Fabric:  completed" || log_error "Corda ↔ Fabric: FAILED ($CF)"
    [ $CC -eq 0 ] && log_success "Corda ↔ Corda:   completed" || log_error "Corda ↔ Corda: FAILED ($CC)"

    local total=$((FF + FC + CF + CC))
    if [ $total -eq 0 ]; then
        log_success "All asset-loan demos finished without script-level errors."
        return 0
    else
        log_warning "Some demos hit non-zero exit; see logs above."
        return 1
    fi
}

main() {
    log_section "Weaver Asset LOAN Docker-based Test Automation"
    log_info "Starting at $(date)"

    if [ "$CLEAN_BUILD_ONLY" = true ]; then
        cleanup_build
        log_section "Build cleanup complete!"
        log_success "Finished at $(date)"
        exit 0
    fi
    if [ "$CLEANUP" = true ]; then
        cleanup_networks
        exit 0
    fi

    check_prerequisites
    setup_protoc
    build_components
    start_networks
    start_relays
    start_drivers
    start_iin_agents
    configure_fabric_cli
    initialize_networks
    create_test_assets
    run_asset_loan_tests

    log_warning "Networks are still running. Run with --cleanup to stop them."

    log_section "Automation Complete!"
    log_success "Finished at $(date)"
}

main "$@"
